---
title: "Intro to Shiny"
author: "Jason Bryer"
date: 2021-11-30
draft: false
categories: ["R", "Meetups"]
tags: ["Annoucement"]
#summary: Recording and slides from the class meetup.
---

Shiny is an R package designed to create web based applications using the R programming language. This talk will introduce the basic framework for creating interactive Shiny applications including user inputs, dynamic plots and tables, reactive programming, and creating data dashboards.

Slides can be viewed here: https://r.bryer.org/shiny/Intro_to_Shiny/

Recording of the talk: https://www.youtube.com/watch?v=W-DrXHqeqz8&t=5s

Source code and resources are on Github here: https://github.com/jbryer/AlbanyRUsers/tree/main/meetups/2021-11-30-Intro_to_Shiny

<iframe width="560" height="315" src="https://www.youtube.com/embed/W-DrXHqeqz8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<!--more-->

Shiny is an R package designed to create web based applications using the R programming language. This talk will introduce the basic framework for creating interactive Shiny applications including user inputs, dynamic plots and tables, reactive programming, and creating data dashboards.

Slides can be viewed here: https://r.bryer.org/shiny/Intro_to_Shiny/

Recording of the talk: https://www.youtube.com/watch?v=W-DrXHqeqz8&t=5s

Source code and resources are on Github here: https://github.com/jbryer/AlbanyRUsers/tree/main/meetups/2021-11-30-Intro_to_Shiny

<iframe width="560" height="315" src="https://www.youtube.com/embed/W-DrXHqeqz8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

