---
title: "Project"
description: ""
weight: 5
editor_options: 
  chunk_output_type: console
---


The purpose of the data project is for you to conduct a reproducible analysis with a data set of your choosing. There are two components to the project, the proposal, which will be graded on a pass/fail basis, and the final report. The outline for each of these are provided in the templates. When submitting the assignments, include the R Markdown file (change the name to include your last name, for example `Bryer-Proposal.Rmd` and `Bryer-Project.Rmd`) along with any supplementary files necessary to run the R Markdown file (e.g. data files, screenshots, etc.). Suggestions for possible data sources are included below, however you are free to use data not listed below. The only requirement is that you are allowed to share the data. Projects will be shared with others on this website so should be presented in a way that other students can reproduce your analysis.

## Project Proposal

The proposal can be more informal using bullet points where necessary and include R code and output. You must address the following areas:

* Research question 
* What are the cases, and how many are there?
* Describe the method of data collection.
* What type of study is this (observational/experiment)?
* Data Source: If you collected the data, state self-collected. If not, provide a citation/link.
* Response: What is the response variable, and what type is it (numerical/categorical)?
* Explanatory: What is the explanatory variable(s), and what type is it (numerical/categorival)?
* Relevant summary statistics 

* [Download project proposal template](https://raw.githubusercontent.com/jbryer/DATA606Fall2020/master/Project/DATA606_proposal_template.Rmd)
* [Download project template](https://raw.githubusercontent.com/jbryer/DATA606Fall2020/master/Project/DATA606_project_template.Rmd)

[Example data project proposal](http://htmlpreview.github.io/?https://github.com/jbryer/DATA606Fall2020/blob/master/Project/Example_proposal.html) ([Source Rmarkdown file](https://raw.githubusercontent.com/jbryer/DATA606Fall2020/master/Project/Example_proposal.Rmd))


## Final Project

* You are required to attend ONLY ONE of those time slots. You will do your presentation, watch the other presentations, and provide peer feedback (will be shared anonymously afterward).

[Click here to sign-up for a presentation slot](https://docs.google.com/spreadsheets/d/1osprAt7AIA29pB_pq22vThcS3lvZQf8ic38s9D3jV5E/edit?usp=sharing). Please pick one timeslot. You need to stay for all presentations during that time as there will be a peer feedback form provided. **There is a maximum of 8 slots per time period.**


#### Checklist / Suggested Outline

* Abstract (no more than 300 words)
* Overview slide
	* Context on the data collection
	* Description of the dependent variable (what is being measured)
	* Description of the independent variable (what is being measured; include at least 2 variables)
	* Research question
* Summary statistics
* Include appropriate data visualizations.
* Statistical output
	* Include the appropriate statistics for your method used.
	* For null hypothesis tests (e.g. t-test, chi-squared, ANOVA, etc.), state the null and alternative hypotheses along with relevant statistic and p-value (and confidence interval if appropriate).
	* For regression models, include the regression output and interpret the R-squared value.
* Conclusion
	* Why is this analysis important?
	* Limitations of the analysis?

#### Rubric

```{r, eval = TRUE, echo = FALSE, results = 'asis'}
rubric <- readxl::read_excel('../../../Project/Data_Project_Rubric.xlsx')
# row.names(rubric) <- rubric$Domain
# rubric$Domain <- NULL
knitr::kable(rubric, row.names = FALSE)
```



## Example Data Sources

You are not to use data sources used in class or the textbooks. Possible data sources include, but are not limited to:

* FiveThirtyEight [https://github.com/fivethirtyeight/data](https://github.com/fivethirtyeight/data)
* RStudio data sources [http://blog.rstudio.org/2014/07/23/new-data-packages/](http://blog.rstudio.org/2014/07/23/new-data-packages/)
* Analyze Survey Data for Free (ASDFree) has many open data sources that can be used [http://www.asdfree.com/](http://www.asdfree.com/)
* The World Bank Data Catalog [http://datacatalog.worldbank.org/](http://datacatalog.worldbank.org/)
* Google Public Data search engine [http://www.google.com/publicdata/directory](http://www.google.com/publicdata/directory)
* Vanderbilt data sources [http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets](http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets)
* Programme of International Student Assessment (PISA) [http://www.oecd.org/pisa/](http://www.oecd.org/pisa/)
* Behavioral Risk Factor Surveillance System (BRFSS) [http://www.cdc.gov/brfss/](http://www.cdc.gov/brfss/)
* World Values Survey [http://www.worldvaluessurvey.org/wvs.jsp](http://www.worldvaluessurvey.org/wvs.jsp)
* American National Election Survey (ANES) [http://www.electionstudies.org/](http://www.electionstudies.org/)
* General Social Survey (GSS) [http://www3.norc.org/GSS+Website/](http://www3.norc.org/GSS+Website/)
* Integrated Postsecondary Education Data System (IPEDS) [https://nces.ed.gov/ipeds/](https://nces.ed.gov/ipeds/)
* U.S. Census and American Community Survey [https://cran.r-project.org/web/packages/acs/index.html](https://cran.r-project.org/web/packages/acs/index.html)
